### ISSUE TITLE
Audio not playing for transcript

### ISSUE THREAD

**Issue by singlesoliloquy** [WGBH-MLA/transcript-editor#139]
**Describe the bug**

**To Reproduce**
1. Go to [http://fixitplus.americanarchive.org/transcripts/cpb-aacip_153-278sfbrn](http://fixitplus.americanarchive.org/transcripts/cpb-aacip_153-278sfbrn)
2. See the icon spin where the audio should be

**Expected behavior**
Audio plays for the transcripts

**Screenshots**
![Screen Shot 2021-11-12 at 11.28.07 AM.png](https://images.zenhubusercontent.com/5e5e7f2e572e74e6537e269f/27f0ccb0-5078-43eb-948b-797f62f429f6)

**Comment by singlesoliloquy** [comment]
Other users with same problem.

Hope you’re doing well!  I still have a dedicated volunteer who comes in twice a week to fix LPB transcripts on FixIt+.  We’re noticing that we can’t hear the sound on the transcripts.  Here’s an example - [http://fixitplus.americanarchive.org/transcripts/cpb-aacip-17-365489s9](http://fixitplus.americanarchive.org/transcripts/cpb-aacip-17-365489s9)
 
Do you mind checking to see if there’s an issue with FixIt+ or let me know if this is something on our end?

**Comment by foglabs-zen** [comment]
Because the streaming update on AAPB broke the audio playing of video records on fixit+ (fixit does not use videojs to play, it uses a vanilla html5 audio element with various custom js attached to it).

Done when fixit is either updated to talk to Ci itself, via the now-old asset_download method, or rewritten to handle hls streams and maintain the player and transcripts integrated functionality as it currently stands.

Talked with @singlesoliloquy , going to go with the asset_download approach
