### ISSUE TITLE
Update json builder to generate AAPB formatted json transcripts

### ISSUE THREAD

**Issue by sroosa** [WGBH-MLA/transcript-editor#72]
Update: transcript-editor/app/views/transcripts/show.json.jbuilder

Sadie can provide an example AAPB formatted json transcript, so we can try to align the output from this system more with that. It would be nice not to have to run further scripts on the output before these json files get used by AAPB.

**Comment by jasoncorum** [comment]
@sroosa - so, the issue with the PR that I tried to merge is that the front end view relies on `transcript-editor/app/views/transcripts/show.json.jbuilder` in the original format. The code in the PR overwrote that entirely which caused the view and some JS to fail. Would it be OK to just tack on the 'parts' formatting to the end of `transcript-editor/app/views/transcripts/show.json.jbuilder`? Or should we render a whole new endpoint entirely where we have a totally clean AAPB formatted json transcript? Putting this here more for remembering what the issue is for Monday!

**Comment by jasoncorum** [comment]
NOTE: We decided to create a new appb transcript endpoint.

**Comment by sroosa** [comment]
Closed by #79
